# Generated by Django 5.0 on 2025-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_value',
            field=models.FloatField(default=0),
        ),
    ]
